version: '3'

services:
  nextjs-ui:
    build:
      context: ./
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo:4
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root